baseURL = "https://hannowybrenmook.netlify.app"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northendlab-hugo"
title = "Tools for Mac"
[[menu.footer]]
URL = "contact"
name = "Add your Tool"
weight = 1
[[menu.main]]
URL = "contact"
name = "Add Tool"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Themefisher"
contact_form_action = "#"
copyright = "&copy; 2020 ToolsForMac All Rights Reserved"
description = "A currated list of MacOS tools to get the most out of your Mac"
google_analitycs_id = ""
google_tag_manager = ""
home = "Home"
logo = "images/logo.svg"
[params.banner]
bgImage = "images/banner/banner-bg.svg"
image = "images/banner/illustration.svg"
title = "A currated list of MacOS tools to get the most out of your Mac"
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = true
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = false
[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-github"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
